#!/bin/bash

#DEBHELPER#

# Add Grafana repo
if [ ! -f /etc/apt/sources.list.d/grafana.list ]; then
    echo "Adding grafana repo"
    wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
    echo "deb https://packages.grafana.com/oss/deb stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
fi

# Install Grafana
if ! dpkg-query -l grafana >/dev/null 2>&1; then
    echo "Installing Grafana package"
    sudo apt update && sudo apt install -y grafana
fi

# Enable Grafana web UI port
echo "Enabling TCP port 3000"
sudo ufw allow 3000/tcp

# Install Plugins
echo Installing grafana plugins
sudo grafana-cli plugins install ae3e-plotly-panel

# Install Dashboards
echo Loading Dashboards
sudo mkdir /var/lib/grafana/dashboards
sudo chown grafana:grafana /var/lib/grafana/dashboards
sudo cp wlanpi-dashboard.json /var/lib/grafana/dashboards/wlanpi-dashboard.json
sudo cp wlanpi-wispy.json /var/lib/grafana/dashboards/wlanpi-wispy.json
sudo chown -R grafana:grafana /var/lib/grafana/dashboards/*

# Provisioning
sudo cp wlanpi-dashboards.yaml /etc/grafana/provisioning/dashboards/wlanpi-dashboards.yaml

# Generate Grafana API Token and set GRAFANA_TOKEN env var
curl -X POST http://admin:admin@localhost:3000/api/serviceaccounts -H "Accept: application/json" -H "Content-Type: application/json" -d '{"name": "wlanpi", "role": "Admin", "isDisabled": false}'
### Returns:
#    {"id":2,"name":"wlanpi","login":"sa-wlanpi","orgId":1,"isDisabled":false,"role":"Admin","tokens":0,"avatarUrl":""}
#   Need to get the "id" value
curl -X POST http://admin:admin@localhost:3000/api/serviceaccounts/2/tokens -H "Accept: application/json" -H "Content-Type: application/json" -d '{"name": "wlanpi", "role": "Admin"}'
### Returns:
#    {"id":2,"name":"wlanpi","key":"glsa_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX_XXXXXXXX"}
#   Need to get the "key" and store it in the env var GRAFANA_TOKEN

# Start Grafana service
echo "Enabling grafana-server service"
sudo /bin/systemctl enable grafana-server

# Start streamers (these should move to services)
./stream-scan.sh &
./stream-assoc.sh &
./wispy-5ghz.sh &

