#!/bin/bash

#DEBHELPER#

# Add Grafana repo
if [ ! -f /etc/apt/sources.list.d/grafana.list ]; then
    echo "Adding grafana repo"
    wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
    echo "deb https://packages.grafana.com/oss/deb stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
fi

# Install Grafana
if ! dpkg-query -l grafana >/dev/null 2>&1; then
    echo "Installing Grafana package"
    sudo apt update && sudo apt install -y grafana
fi

# Enable Grafana web UI port
echo "Enabling TCP port 3000"
sudo ufw allow 3000/tcp

# Install Plugins
echo Installing grafana plugins
sudo grafana-cli plugins install ae3e-plotly-panel

# Install Dashboards
echo Loading Dashboards
sudo mkdir /var/lib/grafana/dashboards
sudo chown grafana:grafana /var/lib/grafana/dashboards
sudo cp wlanpi-dashboard.json /var/lib/grafana/dashboards/wlanpi-dashboard.json
sudo cp wlanpi-wispy.json /var/lib/grafana/dashboards/wlanpi-wispy.json
sudo chown -R grafana:grafana /var/lib/grafana/dashboards/*

# Provisioning
sudo cp wlanpi-dashboards.yaml /etc/grafana/provisioning/dashboards/wlanpi-dashboards.yaml

# Start Grafana service
echo "Enabling grafana-server service"
sudo /bin/systemctl enable grafana-server
